function H = getAccTransforms(thetadotdot,W)

for i = 1:length(thetas)
    % Odds % T_01 T_23 T_45 T_67
    if (mod(i,2)~=0) 
        H(:,:,i) = [0    -thetadotdot(i)   0       0     ; ...
                    0       0       0       0 ; ...
                    thetadotdot(i)   0   0       0     ; ...
                    0       0       0      0   ] + W(:,:,i)^2;  %need to check if its ^2 or .^2
    % Evens % T_12 T_34 T_56
    else
        H(:,:,i) = [0   0   0       0     ; ...
                    0       0       -thetadotdot(i)      0     ; ...
                    0	thetadotdot(i)	0       0     ; ...
                    0       0       0       1    ]+ W(:,:,i)^2;
    end
end
end