function W = getVelTransforms(thetadot)

for i = 1:length(thetadot)
    % Odds % T_01 T_23 T_45 T_67
    if (mod(i,2)~=0) 
        W(:,:,i) = [0    -thetadot(i)   0       0     ; ...
                    0       0       0       0 ; ...
                    thetadot(i)   0   0       0     ; ...
                    0       0       0      0   ];
    % Evens % T_12 T_34 T_56
    else
        W(:,:,i) = [0   0   0       0     ; ...
                    0       0       -thetadot(i)      0     ; ...
                    0	thetadot(i)	0       0     ; ...
                    0       0       0       1    ];
    end
end
end