function W = getVelTransforms(thetadot)

for i = 1:length(thetadot)
   
    if (mod(i,2)==0) 
        W(:,:,i) = [0    0   thetadot(i)       0     ; ...
                     0      0       0       0 ; ...
                    -thetadot(i)  0   0       0     ; ...
                    0       0       0      0   ];
   
    else
        W(:,:,i) = [0       0       0       0     ; ...
                    0       0       -thetadot(i)      0     ; ...
                    0	thetadot(i)	0       0     ; ...
                    0       0       0       1    ];
    end
end
end